/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package racingcar;

import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author wasinee
 */
public class CharacterCar extends javax.swing.JFrame {

    /**
     * Creates new form CharacterCar
     */
    public CharacterCar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonCar7 = new javax.swing.JButton();
        jButtonCar1 = new javax.swing.JButton();
        jButtonCar4 = new javax.swing.JButton();
        jButtonCar8 = new javax.swing.JButton();
        jButtonCar5 = new javax.swing.JButton();
        jButtonCar2 = new javax.swing.JButton();
        jButtonCar9 = new javax.swing.JButton();
        jButtonCar6 = new javax.swing.JButton();
        jButtonCar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 770));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(35, 41, 49));

        jLabel1.setBackground(new java.awt.Color(242, 38, 19));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("R  A  C  I  N  G       C  A  R");

        jLabelClose.setBackground(new java.awt.Color(242, 38, 19));
        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.setText("x");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setBackground(new java.awt.Color(242, 38, 19));
        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMin.setText("-");
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelClose)
                .addComponent(jLabelMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 40);

        jPanel2.setBackground(new java.awt.Color(249, 105, 14));
        jPanel2.setLayout(null);

        jButtonCar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/racingcar/car7-1.png"))); // NOI18N
        jButtonCar7.setText("jButton1");
        jPanel2.add(jButtonCar7);
        jButtonCar7.setBounds(60, 480, 310, 220);

        jButtonCar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/racingcar/car1-1.png"))); // NOI18N
        jButtonCar1.setText("jButton1");
        jPanel2.add(jButtonCar1);
        jButtonCar1.setBounds(60, 20, 310, 220);

        jButtonCar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/racingcar/car4-1.png"))); // NOI18N
        jButtonCar4.setText("jButton1");
        jPanel2.add(jButtonCar4);
        jButtonCar4.setBounds(60, 250, 310, 220);

        jButtonCar8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/racingcar/car8-1.png"))); // NOI18N
        jButtonCar8.setText("jButton1");
        jPanel2.add(jButtonCar8);
        jButtonCar8.setBounds(440, 480, 310, 220);

        jButtonCar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/racingcar/car5-1.png"))); // NOI18N
        jButtonCar5.setText("jButton1");
        jPanel2.add(jButtonCar5);
        jButtonCar5.setBounds(440, 250, 310, 220);

        jButtonCar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/racingcar/car2-1.png"))); // NOI18N
        jButtonCar2.setText("jButton1");
        jPanel2.add(jButtonCar2);
        jButtonCar2.setBounds(440, 20, 310, 220);

        jButtonCar9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/racingcar/car9-1.png"))); // NOI18N
        jButtonCar9.setText("jButton1");
        jPanel2.add(jButtonCar9);
        jButtonCar9.setBounds(820, 480, 310, 220);

        jButtonCar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/racingcar/car6-1.png"))); // NOI18N
        jButtonCar6.setText("jButton1");
        jPanel2.add(jButtonCar6);
        jButtonCar6.setBounds(820, 250, 310, 220);

        jButtonCar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/racingcar/car3-1.png"))); // NOI18N
        jButtonCar3.setText("jButton1");
        jPanel2.add(jButtonCar3);
        jButtonCar3.setBounds(820, 20, 310, 220);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 40, 1200, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharacterCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharacterCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharacterCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharacterCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CharacterCar jframe =  new CharacterCar();
                jframe.setPreferredSize(new Dimension(1200, 770));
                jframe.pack();
                jframe.setLocationRelativeTo(null);
                jframe.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCar1;
    private javax.swing.JButton jButtonCar2;
    private javax.swing.JButton jButtonCar3;
    private javax.swing.JButton jButtonCar4;
    private javax.swing.JButton jButtonCar5;
    private javax.swing.JButton jButtonCar6;
    private javax.swing.JButton jButtonCar7;
    private javax.swing.JButton jButtonCar8;
    private javax.swing.JButton jButtonCar9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
